[KL-394] - added component 'filter-bar' for active filters in filters-bar and re…
vokilam-d/tCommerce-web-client pull request #51
Opened 2020-11-12 13:52 UTC by IvanMatador

added component 'filter-bar' for active filters in filters-bar and refreshed styles for active filters

2020-11-15 19:38 UTC, vokilam-d requested changes

2020-11-15 19:38 UTC, vokilam-d commented on src/app/product-list/filter/filter.component.scss
> +    align-items: center;
align-items относится к display: flex, и поэтому должен идти после него

2020-11-15 20:22 UTC, IvanMatador commented on src/app/product-list/filter/filter.component.html
> +  <div class="its-desktop">
*ngIf и *ngFor можно использовать в одном теге?

2020-11-15 20:36 UTC, IvanMatador commented on src/app/product-list/filter/filter.component.scss
> +    white-space: nowrap;
ну white-space же после жирности шрифта)))

2020-11-16 12:14 UTC, vokilam-d requested changes

2020-11-16 12:14 UTC, vokilam-d commented on src/app/product-list/filter-bar/filter-bar.component.scss
> +.filters-bar  {
пробелы лишние

2020-11-16 12:14 UTC, vokilam-d commented on src/app/product-list/filter-bar/filter-bar.component.scss
> +    @include respond-to($media_large) {
медиа-запросы нужно писать после объявления стилей, это для того, чтоб было видно, что они перебивают предыдущие стили:
```
&__element {
  ...: ...;
  ...: ...;

  @response-to {
    ...: ...;
  }
}
```

посмотри как в других файлах это было сделано

2020-11-16 12:14 UTC, vokilam-d commented on src/app/product-list/filter-bar/filter-bar.component.scss
> +    &.clear-all {
мы используем БЭМ для того, чтоб убрать вложенность, я писал в чате об этом

2020-11-16 12:14 UTC, vokilam-d commented on src/app/product-list/filter-bar/filter-bar.component.html
> +<div class="filters-bar__container" *ngIf="selectedFiltersInBar?.length">
`filters-bar__container`
здесь класс можно просто назвать `filters-bar`

2020-11-16 12:14 UTC, vokilam-d commented on src/app/product-list/filter-bar/filter-bar.component.html
> +    <ul class="filters-bar__filters_box">
почему-то нижнее подчёркивание вместо дефиса

2020-11-16 12:14 UTC, vokilam-d commented on src/app/product-list/filter-bar/filter-bar.component.html
> +        <button class="clear-all_button" (click)="unselectAll()">
БЭМ:
элемент отделяется от блока двумя нижними подчёркиваниями, а не одним

2020-11-16 12:14 UTC, vokilam-d commented on src/app/product-list/filter-bar/filter-bar.component.ts
> +  get activeFilters(): FilterDto[] {
поменяй порядок свойств в классе, как я писал в чате

2020-11-16 12:14 UTC, vokilam-d commented on src/app/product-list/filter-bar/filter-bar.component.ts
> +              }
исправь отступ

2020-11-16 12:14 UTC, vokilam-d commented on src/app/product-list/filter-bar/filter-bar.component.ts
> +      if (this.filters) {
исправь отступ всего `if`

2020-11-16 12:14 UTC, vokilam-d commented on src/app/product-list/filter-bar/filter-bar.component.ts
> +        })
нет точки с запятой

2020-11-16 12:14 UTC, vokilam-d commented on src/app/product-list/filter-bar/filter-bar.component.scss
> +    align-items: center;
`align-items` относится к `display: inline-flex;`, они должны быть рядом

2020-11-16 12:14 UTC, vokilam-d commented on src/app/product-list/filter-bar/filter-bar.component.scss
> +    align-items: center;
`align-items` относится к `display: inline-flex;`, они должны быть рядом

2020-11-16 12:14 UTC, vokilam-d commented on src/app/product-list/filter-bar/filter-bar.component.scss
> +
пустая строка

2020-11-16 12:14 UTC, vokilam-d commented on src/app/product-list/filter-bar/filter-bar.component.scss
> +    color: rgba($red, 1.1);
1.1 - неправильное значение

2020-11-16 12:14 UTC, vokilam-d commented on src/app/product-list/filter/filter.component.scss
> +    color: rgba($dark, 1.1);
`1.1` - неправильное значение

2020-11-16 12:14 UTC, vokilam-d commented on src/app/product-list/product-list.component.scss
> +  height: auto;
`height` относится к `min-height`, они должны быть рядом

2020-11-16 18:28 UTC, vokilam-d requested changes

2020-11-16 18:28 UTC, vokilam-d commented on src/app/product-list/filter-bar/filter-bar.component.html
> +      <button class="filters-bar__item--btn" (click)="unselectAll()">
`filters-bar__item--btn` - такого не может быть, ты же сегодня спрашивал, и я писал, что модификатор используется только вместе с классом, который он модифицирует.
То есть должно быть `filters-bar__item filters-bar__item--btn`.
Но понятно, что это не подходит, это же не `item`,  поэтому  просто сделай его элементом, например `filters-bar__clear-btn`

2020-11-16 18:28 UTC, vokilam-d commented on src/app/product-list/filter-bar/filter-bar.component.scss
> +  &__clear-all {
этот класс нигде не используется

2020-11-16 18:28 UTC, vokilam-d commented on src/app/product-list/filter-bar/filter-bar.component.scss
> +      &:hover {
с этой строки по 56 съехали отступы, посмотри как они делаются в других файлах

2020-11-16 18:28 UTC, vokilam-d commented on src/app/product-list/filter-bar/filter-bar.component.ts
> +import { FilterDto, FilterValueDto} from 'src/app/shared/dtos/filter.dto';
пробел пропал перед `}`

2020-11-16 18:28 UTC, vokilam-d commented on src/app/product-list/product-list.component.ts
> +import { FilterBarComponent } from './filter-bar/filter-bar.component';
импорт нигде не используешь

2020-11-19 20:46 UTC, closed without merging