Kl 414 new styles base
vokilam-d/tCommerce-web-client pull request #62
Opened 2020-11-25 13:14 UTC by IvanMatador

2020-11-29 15:57 UTC, vokilam-d requested changes

2020-11-29 15:57 UTC, vokilam-d commented on src/app/blog-toolbar/blog-toolbar.component.html
> +        <i class="mbi mbi-ios-arrow-right category__icon hidden"></i>
Если ты хочешь навсегда скрыть элемент, то не надо для него прописывать в стилях `display: none`. Просто сразу удаляй его и всё

А уж тем более не надо для этого создавать отдельный класс, который ты используешь только в одном этом месте

2020-11-29 15:57 UTC, vokilam-d commented on src/app/breadcrumbs/breadcrumbs.component.scss
> +       border: solid #aaa;
отступ съехал

2020-11-29 15:57 UTC, vokilam-d commented on src/app/pages/category/category.component.scss
> +  /*     color: $linkMain;
не оставляй ненужные комментарии

2020-11-29 15:57 UTC, vokilam-d commented on src/app/product-list-item/product-list-item.component.scss
> +  &__link {
по-моему, это css-правило здесь лишнее

2020-11-29 15:57 UTC, vokilam-d commented on src/app/product-list/product-list.component.scss
> +      position: static;
почему поменял местами свойства?
было ж вроде правильно

2020-11-29 15:57 UTC, vokilam-d commented on src/assets/styles/base/_base.scss
> +  color: $linkMain !important;
`!important` в цсс - это bad practice, никогда не используй его, т.к. такой код становится неподдерживаемым

2020-11-29 15:57 UTC, vokilam-d commented on src/assets/styles/base/_base.scss
> +  &:hover, &__hover:hover {
ты нигде не используешь класс `main-link__hover`

2020-11-29 15:57 UTC, vokilam-d commented on src/assets/styles/base/_base.scss
> +    color: $linkMainHover !important;
использование `!important` это bad practice, никогда не используй его, т.к. такой код становится неподдерживаемым

2020-11-29 15:57 UTC, vokilam-d commented on src/assets/styles/base/_base.scss
> +  color: $linkMain !important;
ты потерял свойство `cursor: pointer`, оно было в глобальных стилях для ссылок, добавь его

2020-11-29 15:57 UTC, vokilam-d commented on src/assets/styles/base/_base.scss
> +.black-link {
`.black-link` отличается от `.main-link` всего лишь одним свойством.
Создавать отдельный класс для такого - излишество, тут идеально подходит БЭМ-модификатор.

можно просто сделать `main-link--black` и перебить там это одно свойство `color`

2020-11-29 15:57 UTC, vokilam-d commented on src/assets/styles/base/_base.scss
> -
Вот эти строчки (46-53) верни, просто это стили для ссылок, которые задаются через админку (описание товаров, или блог-посты).

Эти ссылки вставляются потом на страницу динамически, поэтому ангуляровские стили из компонентов или глобальных классов на них не распространяются, им надо вот такие глобальные общие задавать

2020-11-29 15:57 UTC, vokilam-d commented on src/assets/styles/base/_base.scss
> +    color: $primary
точки с запятой нет

2020-11-29 15:57 UTC, vokilam-d commented on src/assets/styles/base/_base.scss
> +.primary-link {
Название не очень удачное, т.к. по смыслу `primary-link` сильно пересекается с `main-link`. Из их названий совсем не понятно для каких ситуаций нужно использовать одно, а для каких - другое. А понятно должно быть.

Плюс, думаю, не очень хорошая идея делать для этого глобальный класс, т.к. он используется всего в одном компоненте

Так что ты смело можешь эти стили перенести для класса `.phones__phone`. Тем более свойство `transition` там уже есть, ты его здесь продублировал

2020-11-29 17:36 UTC, IvanMatador commented on src/app/blog-toolbar/blog-toolbar.component.html
> +        <i class="mbi mbi-ios-arrow-right category__icon hidden"></i>
Это предварительное действие, на рассуждение всех причасных, поэтому сначала скрываю, а при подтверждении - удаляем. Согласен?

2020-12-01 16:38 UTC, vokilam-d requested changes

2020-12-01 16:38 UTC, vokilam-d commented on src/app/header/header.component.html
> +          <a class="phones__phone primary-link" href="tel:+380502627214">+38 (050) 26-27-214</a>
`primary-link` классы забыл убрать

2020-12-01 16:38 UTC, vokilam-d commented on src/app/header/header.component.scss
> +      color: $primary;
кажется здесь что-то не то:)
у img ведь нет `color`

2020-12-01 16:38 UTC, vokilam-d commented on src/assets/styles/base/_base.scss
> +  &:visited, &:active {
каждый селектор у нас с новой строчки пишется

2020-12-01 16:38 UTC, vokilam-d commented on src/assets/styles/base/_base.scss
> +    color: $dark;
посещённые `.main-link--black` ссылки тоже стали синие
думаю, здесь тоже просто нужно добавить:
```
&:visited, &:active {
  color: $dark;
}
```

![image](https://user-images.githubusercontent.com/22540525/100769042-36de8b80-3404-11eb-8510-9e0fd98382f6.png)

2020-12-01 16:40 UTC, vokilam-d requested changes

2020-12-01 16:40 UTC, vokilam-d commented on src/assets/styles/base/_base.scss
>      color: $blue;
отут плз поменяй на `$linkMain`

2020-12-01 16:40 UTC, vokilam-d commented on src/assets/styles/base/_base.scss
>        color: darken($blue, 10%);
и отут плз поменяй на `$linkMainHover`

2020-12-01 17:33 UTC, IvanMatador commented on src/app/header/header.component.scss
> +      color: $primary;
Это же не к img щтносится, а к phones__phone (строки с 209 по 220)

2020-12-01 17:37 UTC, vokilam-d commented on src/app/header/header.component.scss
> +      color: $primary;
аа сори, схлопнулось и показалось

2020-12-06 14:58 UTC, vokilam-d approved these changes

2020-12-06 14:58 UTC, merged

2020-12-06 15:07 UTC, vokilam-d commented
deployed